##############################################################################################
### sub-playbook to deploy the docker images needed for the pfcwd test to fanout swtich
### to run separately:
### ansible-playbook -i lab fanout.yml -l ${FANOUT} --become --tags check_pfcwd_config -vvvv
################################################################################################

- name: Check docker ps status
  action: apswitch template=mlnx_check_pfcwd_fanout.j2
  connection: switch
  register: output
  args:
    login: "{{ switch_login['MLNX-OS'] }}"

- set_fact:
    dockers_running: "{{ 'pfc_storm:latest' in output.stdout and 'Up' in output.stdout }}"

- fail: msg="PFCWD dockers are not running"
  when: not dockers_running
